export const icons = [
  {
    id: "1",
    alias4: "500px",
    alias5: "500px",
    prefix: "fab",
    unicode: "f26e",
  },
  {
    id: "2",
    alias4: "address-book-o",
    alias5: "address-book",
    prefix: "fa",
    unicode: "f2b9",
  },
  {
    id: "3",
    alias4: "address-card-o",
    alias5: "address-card",
    prefix: "fa",
    unicode: "f2bb",
  },
  { id: "4", alias4: "adn", alias5: "adn", prefix: "fab", unicode: "f170" },
  {
    id: "5",
    alias4: "amazon",
    alias5: "amazon",
    prefix: "fab",
    unicode: "f270",
  },
  {
    id: "6",
    alias4: "android",
    alias5: "android",
    prefix: "fab",
    unicode: "f17b",
  },
  {
    id: "7",
    alias4: "angellist",
    alias5: "angellist",
    prefix: "fab",
    unicode: "f209",
  },
  {
    id: "8",
    alias4: "apple",
    alias5: "apple",
    prefix: "fab",
    unicode: "f179",
  },
  {
    id: "9",
    alias4: "area-chart",
    alias5: "chart-area",
    prefix: "fas",
    unicode: "f1fe",
  },
  {
    id: "10",
    alias4: "arrow-circle-o-down",
    alias5: "arrow-alt-circle-down",
    prefix: "fa",
    unicode: "f358",
  },
  {
    id: "11",
    alias4: "arrow-circle-o-left",
    alias5: "arrow-alt-circle-left",
    prefix: "fa",
    unicode: "f359",
  },
  {
    id: "12",
    alias4: "arrow-circle-o-right",
    alias5: "arrow-alt-circle-right",
    prefix: "fa",
    unicode: "f35a",
  },
  {
    id: "13",
    alias4: "arrow-circle-o-up",
    alias5: "arrow-alt-circle-up",
    prefix: "fa",
    unicode: "f35b",
  },
  {
    id: "14",
    alias4: "arrows",
    alias5: "arrows-alt",
    prefix: "fas",
    unicode: "f0b2",
  },
  {
    id: "15",
    alias4: "arrows-alt",
    alias5: "expand-arrows-alt",
    prefix: "fas",
    unicode: "f31e",
  },
  {
    id: "16",
    alias4: "arrows-h",
    alias5: "arrows-alt-h",
    prefix: "fas",
    unicode: "f337",
  },
  {
    id: "17",
    alias4: "arrows-v",
    alias5: "arrows-alt-v",
    prefix: "fas",
    unicode: "f338",
  },
  {
    id: "18",
    alias4: "asl-interpreting",
    alias5: "american-sign-language-interpreting",
    prefix: "fas",
    unicode: "f2a3",
  },
  {
    id: "19",
    alias4: "automobile",
    alias5: "car",
    prefix: "fas",
    unicode: "f1b9",
  },
  {
    id: "20",
    alias4: "bandcamp",
    alias5: "bandcamp",
    prefix: "fab",
    unicode: "f2d5",
  },
  {
    id: "21",
    alias4: "bank",
    alias5: "university",
    prefix: "fas",
    unicode: "f19c",
  },
  {
    id: "22",
    alias4: "bar-chart",
    alias5: "chart-bar",
    prefix: "fa",
    unicode: "f080",
  },
  {
    id: "23",
    alias4: "bar-chart-o",
    alias5: "chart-bar",
    prefix: "fa",
    unicode: "f080",
  },
  {
    id: "24",
    alias4: "bathtub",
    alias5: "bath",
    prefix: "fas",
    unicode: "f2cd",
  },
  {
    id: "25",
    alias4: "battery",
    alias5: "battery-full",
    prefix: "fas",
    unicode: "f240",
  },
  {
    id: "26",
    alias4: "battery-0",
    alias5: "battery-empty",
    prefix: "fas",
    unicode: "f244",
  },
  {
    id: "27",
    alias4: "battery-1",
    alias5: "battery-quarter",
    prefix: "fas",
    unicode: "f243",
  },
  {
    id: "28",
    alias4: "battery-2",
    alias5: "battery-half",
    prefix: "fas",
    unicode: "f242",
  },
  {
    id: "29",
    alias4: "battery-3",
    alias5: "battery-three-quarters",
    prefix: "fas",
    unicode: "f241",
  },
  {
    id: "30",
    alias4: "battery-4",
    alias5: "battery-full",
    prefix: "fas",
    unicode: "f240",
  },
  {
    id: "31",
    alias4: "behance",
    alias5: "behance",
    prefix: "fab",
    unicode: "f1b4",
  },
  {
    id: "32",
    alias4: "behance-square",
    alias5: "behance-square",
    prefix: "fab",
    unicode: "f1b5",
  },
  {
    id: "33",
    alias4: "bell-o",
    alias5: "bell",
    prefix: "fa",
    unicode: "f0f3",
  },
  {
    id: "34",
    alias4: "bell-slash-o",
    alias5: "bell-slash",
    prefix: "fa",
    unicode: "f1f6",
  },
  {
    id: "35",
    alias4: "bitbucket",
    alias5: "bitbucket",
    prefix: "fab",
    unicode: "f171",
  },
  {
    id: "36",
    alias4: "bitbucket-square",
    alias5: "bitbucket",
    prefix: "fab",
    unicode: "f171",
  },
  {
    id: "37",
    alias4: "bitcoin",
    alias5: "btc",
    prefix: "fab",
    unicode: "f15a",
  },
  {
    id: "38",
    alias4: "black-tie",
    alias5: "black-tie",
    prefix: "fab",
    unicode: "f27e",
  },
  {
    id: "39",
    alias4: "bluetooth",
    alias5: "bluetooth",
    prefix: "fab",
    unicode: "f293",
  },
  {
    id: "40",
    alias4: "bluetooth-b",
    alias5: "bluetooth-b",
    prefix: "fab",
    unicode: "f294",
  },
  {
    id: "41",
    alias4: "bookmark-o",
    alias5: "bookmark",
    prefix: "fa",
    unicode: "f02e",
  },
  {
    id: "42",
    alias4: "btc",
    alias5: "btc",
    prefix: "fab",
    unicode: "f15a",
  },
  {
    id: "43",
    alias4: "building-o",
    alias5: "building",
    prefix: "fa",
    unicode: "f1ad",
  },
  {
    id: "44",
    alias4: "buysellads",
    alias5: "buysellads",
    prefix: "fab",
    unicode: "f20d",
  },
  {
    id: "45",
    alias4: "cab",
    alias5: "taxi",
    prefix: "fas",
    unicode: "f1ba",
  },
  {
    id: "46",
    alias4: "calendar",
    alias5: "calendar-alt",
    prefix: "fas",
    unicode: "f073",
  },
  {
    id: "47",
    alias4: "calendar-check-o",
    alias5: "calendar-check",
    prefix: "fa",
    unicode: "f274",
  },
  {
    id: "48",
    alias4: "calendar-minus-o",
    alias5: "calendar-minus",
    prefix: "fa",
    unicode: "f272",
  },
  {
    id: "49",
    alias4: "calendar-o",
    alias5: "calendar",
    prefix: "fa",
    unicode: "f133",
  },
  {
    id: "50",
    alias4: "calendar-plus-o",
    alias5: "calendar-plus",
    prefix: "fa",
    unicode: "f271",
  },
  {
    id: "51",
    alias4: "calendar-times-o",
    alias5: "calendar-times",
    prefix: "fa",
    unicode: "f273",
  },
  {
    id: "52",
    alias4: "caret-square-o-down",
    alias5: "caret-square-down",
    prefix: "fa",
    unicode: "f150",
  },
  {
    id: "53",
    alias4: "caret-square-o-left",
    alias5: "caret-square-left",
    prefix: "fa",
    unicode: "f191",
  },
  {
    id: "54",
    alias4: "caret-square-o-right",
    alias5: "caret-square-right",
    prefix: "fa",
    unicode: "f152",
  },
  {
    id: "55",
    alias4: "caret-square-o-up",
    alias5: "caret-square-up",
    prefix: "fa",
    unicode: "f151",
  },
  {
    id: "56",
    alias4: "cc",
    alias5: "closed-captioning",
    prefix: "fa",
    unicode: "f20a",
  },
  {
    id: "57",
    alias4: "cc-amex",
    alias5: "cc-amex",
    prefix: "fab",
    unicode: "f1f3",
  },
  {
    id: "58",
    alias4: "cc-diners-club",
    alias5: "cc-diners-club",
    prefix: "fab",
    unicode: "f24c",
  },
  {
    id: "59",
    alias4: "cc-discover",
    alias5: "cc-discover",
    prefix: "fab",
    unicode: "f1f2",
  },
  {
    id: "60",
    alias4: "cc-jcb",
    alias5: "cc-jcb",
    prefix: "fab",
    unicode: "f24b",
  },
  {
    id: "61",
    alias4: "cc-mastercard",
    alias5: "cc-mastercard",
    prefix: "fab",
    unicode: "f1f1",
  },
  {
    id: "62",
    alias4: "cc-paypal",
    alias5: "cc-paypal",
    prefix: "fab",
    unicode: "f1f4",
  },
  {
    id: "63",
    alias4: "cc-stripe",
    alias5: "cc-stripe",
    prefix: "fab",
    unicode: "f1f5",
  },
  {
    id: "64",
    alias4: "cc-visa",
    alias5: "cc-visa",
    prefix: "fab",
    unicode: "f1f0",
  },
  {
    id: "65",
    alias4: "chain",
    alias5: "link",
    prefix: "fas",
    unicode: "f0c1",
  },
  {
    id: "66",
    alias4: "chain-broken",
    alias5: "unlink",
    prefix: "fas",
    unicode: "f127",
  },
  {
    id: "67",
    alias4: "check-circle-o",
    alias5: "check-circle",
    prefix: "fa",
    unicode: "f058",
  },
  {
    id: "68",
    alias4: "check-square-o",
    alias5: "check-square",
    prefix: "fa",
    unicode: "f14a",
  },
  {
    id: "69",
    alias4: "chrome",
    alias5: "chrome",
    prefix: "fab",
    unicode: "f268",
  },
  {
    id: "70",
    alias4: "circle-o",
    alias5: "circle",
    prefix: "fa",
    unicode: "f111",
  },
  {
    id: "71",
    alias4: "circle-o-notch",
    alias5: "circle-notch",
    prefix: "fas",
    unicode: "f1ce",
  },
  {
    id: "72",
    alias4: "circle-thin",
    alias5: "circle",
    prefix: "fa",
    unicode: "f111",
  },
  {
    id: "73",
    alias4: "clipboard",
    alias5: "clipboard",
    prefix: "fa",
    unicode: "f328",
  },
  {
    id: "74",
    alias4: "clock-o",
    alias5: "clock",
    prefix: "fa",
    unicode: "f017",
  },
  {
    id: "75",
    alias4: "clone",
    alias5: "clone",
    prefix: "fa",
    unicode: "f24d",
  },
  {
    id: "76",
    alias4: "close",
    alias5: "times",
    prefix: "fas",
    unicode: "f00d",
  },
  {
    id: "77",
    alias4: "cloud-download",
    alias5: "cloud-download-alt",
    prefix: "fas",
    unicode: "f381",
  },
  {
    id: "78",
    alias4: "cloud-upload",
    alias5: "cloud-upload-alt",
    prefix: "fas",
    unicode: "f382",
  },
  {
    id: "79",
    alias4: "cny",
    alias5: "yen-sign",
    prefix: "fas",
    unicode: "f157",
  },
  {
    id: "80",
    alias4: "code-fork",
    alias5: "code-branch",
    prefix: "fas",
    unicode: "f126",
  },
  {
    id: "81",
    alias4: "codepen",
    alias5: "codepen",
    prefix: "fab",
    unicode: "f1cb",
  },
  {
    id: "82",
    alias4: "codiepie",
    alias5: "codiepie",
    prefix: "fab",
    unicode: "f284",
  },
  {
    id: "83",
    alias4: "comment-o",
    alias5: "comment",
    prefix: "fa",
    unicode: "f075",
  },
  {
    id: "84",
    alias4: "commenting",
    alias5: "comment-dots",
    prefix: "fas",
    unicode: "f4ad",
  },
  {
    id: "85",
    alias4: "commenting-o",
    alias5: "comment-dots",
    prefix: "fa",
    unicode: "f4ad",
  },
  {
    id: "86",
    alias4: "comments-o",
    alias5: "comments",
    prefix: "fa",
    unicode: "f086",
  },
  {
    id: "87",
    alias4: "compass",
    alias5: "compass",
    prefix: "fa",
    unicode: "f14e",
  },
  {
    id: "88",
    alias4: "connectdevelop",
    alias5: "connectdevelop",
    prefix: "fab",
    unicode: "f20e",
  },
  {
    id: "89",
    alias4: "contao",
    alias5: "contao",
    prefix: "fab",
    unicode: "f26d",
  },
  {
    id: "90",
    alias4: "copyright",
    alias5: "copyright",
    prefix: "fa",
    unicode: "f1f9",
  },
  {
    id: "91",
    alias4: "creative-commons",
    alias5: "creative-commons",
    prefix: "fab",
    unicode: "f25e",
  },
  {
    id: "92",
    alias4: "credit-card",
    alias5: "credit-card",
    prefix: "fa",
    unicode: "f09d",
  },
  {
    id: "93",
    alias4: "credit-card-alt",
    alias5: "credit-card",
    prefix: "fas",
    unicode: "f09d",
  },
  {
    id: "94",
    alias4: "css3",
    alias5: "css3",
    prefix: "fab",
    unicode: "f13c",
  },
  {
    id: "95",
    alias4: "cutlery",
    alias5: "utensils",
    prefix: "fas",
    unicode: "f2e7",
  },
  {
    id: "96",
    alias4: "dashboard",
    alias5: "tachometer-alt",
    prefix: "fas",
    unicode: "f3fd",
  },
  {
    id: "97",
    alias4: "dashcube",
    alias5: "dashcube",
    prefix: "fab",
    unicode: "f210",
  },
  {
    id: "98",
    alias4: "deafness",
    alias5: "deaf",
    prefix: "fas",
    unicode: "f2a4",
  },
  {
    id: "99",
    alias4: "dedent",
    alias5: "outdent",
    prefix: "fas",
    unicode: "f03b",
  },
  {
    id: "100",
    alias4: "delicious",
    alias5: "delicious",
    prefix: "fab",
    unicode: "f1a5",
  },
  {
    id: "101",
    alias4: "deviantart",
    alias5: "deviantart",
    prefix: "fab",
    unicode: "f1bd",
  },
  {
    id: "102",
    alias4: "diamond",
    alias5: "gem",
    prefix: "fa",
    unicode: "f3a5",
  },
  {
    id: "103",
    alias4: "digg",
    alias5: "digg",
    prefix: "fab",
    unicode: "f1a6",
  },
  {
    id: "104",
    alias4: "dollar",
    alias5: "dollar-sign",
    prefix: "fas",
    unicode: "f155",
  },
  {
    id: "105",
    alias4: "dot-circle-o",
    alias5: "dot-circle",
    prefix: "fa",
    unicode: "f192",
  },
  {
    id: "106",
    alias4: "dribbble",
    alias5: "dribbble",
    prefix: "fab",
    unicode: "f17d",
  },
  {
    id: "107",
    alias4: "drivers-license",
    alias5: "id-card",
    prefix: "fas",
    unicode: "f2c2",
  },
  {
    id: "108",
    alias4: "drivers-license-o",
    alias5: "id-card",
    prefix: "fa",
    unicode: "f2c2",
  },
  {
    id: "109",
    alias4: "dropbox",
    alias5: "dropbox",
    prefix: "fab",
    unicode: "f16b",
  },
  {
    id: "110",
    alias4: "drupal",
    alias5: "drupal",
    prefix: "fab",
    unicode: "f1a9",
  },
  {
    id: "111",
    alias4: "edge",
    alias5: "edge",
    prefix: "fab",
    unicode: "f282",
  },
  {
    id: "112",
    alias4: "eercast",
    alias5: "sellcast",
    prefix: "fab",
    unicode: "f2da",
  },
  {
    id: "113",
    alias4: "empire",
    alias5: "empire",
    prefix: "fab",
    unicode: "f1d1",
  },
  {
    id: "114",
    alias4: "envelope-o",
    alias5: "envelope",
    prefix: "fa",
    unicode: "f0e0",
  },
  {
    id: "115",
    alias4: "envelope-open-o",
    alias5: "envelope-open",
    prefix: "fa",
    unicode: "f2b6",
  },
  {
    id: "116",
    alias4: "envira",
    alias5: "envira",
    prefix: "fab",
    unicode: "f299",
  },
  {
    id: "117",
    alias4: "etsy",
    alias5: "etsy",
    prefix: "fab",
    unicode: "f2d7",
  },
  {
    id: "118",
    alias4: "eur",
    alias5: "euro-sign",
    prefix: "fas",
    unicode: "f153",
  },
  {
    id: "119",
    alias4: "euro",
    alias5: "euro-sign",
    prefix: "fas",
    unicode: "f153",
  },
  {
    id: "120",
    alias4: "exchange",
    alias5: "exchange-alt",
    prefix: "fas",
    unicode: "f362",
  },
  {
    id: "121",
    alias4: "expeditedssl",
    alias5: "expeditedssl",
    prefix: "fab",
    unicode: "f23e",
  },
  {
    id: "122",
    alias4: "external-link",
    alias5: "external-link-alt",
    prefix: "fas",
    unicode: "f35d",
  },
  {
    id: "123",
    alias4: "external-link-square",
    alias5: "external-link-square-alt",
    prefix: "fas",
    unicode: "f360",
  },
  {
    id: "124",
    alias4: "eye",
    alias5: "eye",
    prefix: "fa",
    unicode: "f06e",
  },
  {
    id: "125",
    alias4: "eye-slash",
    alias5: "eye-slash",
    prefix: "fa",
    unicode: "f070",
  },
  {
    id: "126",
    alias4: "eyedropper",
    alias5: "eye-dropper",
    prefix: "fas",
    unicode: "f1fb",
  },
  {
    id: "127",
    alias4: "fa",
    alias5: "font-awesome",
    prefix: "fab",
    unicode: "f2b4",
  },
  {
    id: "128",
    alias4: "facebook",
    alias5: "facebook-f",
    prefix: "fab",
    unicode: "f39e",
  },
  {
    id: "129",
    alias4: "facebook-f",
    alias5: "facebook-f",
    prefix: "fab",
    unicode: "f39e",
  },
  {
    id: "130",
    alias4: "facebook-official",
    alias5: "facebook",
    prefix: "fab",
    unicode: "f09a",
  },
  {
    id: "131",
    alias4: "facebook-square",
    alias5: "facebook-square",
    prefix: "fab",
    unicode: "f082",
  },
  {
    id: "132",
    alias4: "feed",
    alias5: "rss",
    prefix: "fas",
    unicode: "f09e",
  },
  {
    id: "133",
    alias4: "file-archive-o",
    alias5: "file-archive",
    prefix: "fa",
    unicode: "f1c6",
  },
  {
    id: "134",
    alias4: "file-audio-o",
    alias5: "file-audio",
    prefix: "fa",
    unicode: "f1c7",
  },
  {
    id: "135",
    alias4: "file-code-o",
    alias5: "file-code",
    prefix: "fa",
    unicode: "f1c9",
  },
  {
    id: "136",
    alias4: "file-excel-o",
    alias5: "file-excel",
    prefix: "fa",
    unicode: "f1c3",
  },
  {
    id: "137",
    alias4: "file-image-o",
    alias5: "file-image",
    prefix: "fa",
    unicode: "f1c5",
  },
  {
    id: "138",
    alias4: "file-movie-o",
    alias5: "file-video",
    prefix: "fa",
    unicode: "f1c8",
  },
  {
    id: "139",
    alias4: "file-o",
    alias5: "file",
    prefix: "fa",
    unicode: "f15b",
  },
  {
    id: "140",
    alias4: "file-pdf-o",
    alias5: "file-pdf",
    prefix: "fa",
    unicode: "f1c1",
  },
  {
    id: "141",
    alias4: "file-photo-o",
    alias5: "file-image",
    prefix: "fa",
    unicode: "f1c5",
  },
  {
    id: "142",
    alias4: "file-picture-o",
    alias5: "file-image",
    prefix: "fa",
    unicode: "f1c5",
  },
  {
    id: "143",
    alias4: "file-powerpoint-o",
    alias5: "file-powerpoint",
    prefix: "fa",
    unicode: "f1c4",
  },
  {
    id: "144",
    alias4: "file-sound-o",
    alias5: "file-audio",
    prefix: "fa",
    unicode: "f1c7",
  },
  {
    id: "145",
    alias4: "file-text",
    alias5: "file-alt",
    prefix: "fas",
    unicode: "f15c",
  },
  {
    id: "146",
    alias4: "file-text-o",
    alias5: "file-alt",
    prefix: "fa",
    unicode: "f15c",
  },
  {
    id: "147",
    alias4: "file-video-o",
    alias5: "file-video",
    prefix: "fa",
    unicode: "f1c8",
  },
  {
    id: "148",
    alias4: "file-word-o",
    alias5: "file-word",
    prefix: "fa",
    unicode: "f1c2",
  },
  {
    id: "149",
    alias4: "file-zip-o",
    alias5: "file-archive",
    prefix: "fa",
    unicode: "f1c6",
  },
  {
    id: "150",
    alias4: "files-o",
    alias5: "copy",
    prefix: "fa",
    unicode: "f0c5",
  },
  {
    id: "151",
    alias4: "firefox",
    alias5: "firefox",
    prefix: "fab",
    unicode: "f269",
  },
  {
    id: "152",
    alias4: "first-order",
    alias5: "first-order",
    prefix: "fab",
    unicode: "f2b0",
  },
  {
    id: "153",
    alias4: "flag-o",
    alias5: "flag",
    prefix: "fa",
    unicode: "f024",
  },
  {
    id: "154",
    alias4: "flash",
    alias5: "bolt",
    prefix: "fas",
    unicode: "f0e7",
  },
  {
    id: "155",
    alias4: "flickr",
    alias5: "flickr",
    prefix: "fab",
    unicode: "f16e",
  },
  {
    id: "156",
    alias4: "floppy-o",
    alias5: "save",
    prefix: "fa",
    unicode: "f0c7",
  },
  {
    id: "157",
    alias4: "folder-o",
    alias5: "folder",
    prefix: "fa",
    unicode: "f07b",
  },
  {
    id: "158",
    alias4: "folder-open-o",
    alias5: "folder-open",
    prefix: "fa",
    unicode: "f07c",
  },
  {
    id: "159",
    alias4: "font-awesome",
    alias5: "font-awesome",
    prefix: "fab",
    unicode: "f2b4",
  },
  {
    id: "160",
    alias4: "fonticons",
    alias5: "fonticons",
    prefix: "fab",
    unicode: "f280",
  },
  {
    id: "161",
    alias4: "fort-awesome",
    alias5: "fort-awesome",
    prefix: "fab",
    unicode: "f286",
  },
  {
    id: "162",
    alias4: "forumbee",
    alias5: "forumbee",
    prefix: "fab",
    unicode: "f211",
  },
  {
    id: "163",
    alias4: "foursquare",
    alias5: "foursquare",
    prefix: "fab",
    unicode: "f180",
  },
  {
    id: "164",
    alias4: "free-code-camp",
    alias5: "free-code-camp",
    prefix: "fab",
    unicode: "f2c5",
  },
  {
    id: "165",
    alias4: "frown-o",
    alias5: "frown",
    prefix: "fa",
    unicode: "f119",
  },
  {
    id: "166",
    alias4: "futbol-o",
    alias5: "futbol",
    prefix: "fa",
    unicode: "f1e3",
  },
  {
    id: "167",
    alias4: "gbp",
    alias5: "pound-sign",
    prefix: "fas",
    unicode: "f154",
  },
  {
    id: "168",
    alias4: "ge",
    alias5: "empire",
    prefix: "fab",
    unicode: "f1d1",
  },
  {
    id: "169",
    alias4: "gear",
    alias5: "cog",
    prefix: "fas",
    unicode: "f013",
  },
  {
    id: "170",
    alias4: "gears",
    alias5: "cogs",
    prefix: "fas",
    unicode: "f085",
  },
  {
    id: "171",
    alias4: "get-pocket",
    alias5: "get-pocket",
    prefix: "fab",
    unicode: "f265",
  },
  { id: "172", alias4: "gg", alias5: "gg", prefix: "fab", unicode: "f260" },
  {
    id: "173",
    alias4: "gg-circle",
    alias5: "gg-circle",
    prefix: "fab",
    unicode: "f261",
  },
  {
    id: "174",
    alias4: "git",
    alias5: "git",
    prefix: "fab",
    unicode: "f1d3",
  },
  {
    id: "175",
    alias4: "git-square",
    alias5: "git-square",
    prefix: "fab",
    unicode: "f1d2",
  },
  {
    id: "176",
    alias4: "github",
    alias5: "github",
    prefix: "fab",
    unicode: "f09b",
  },
  {
    id: "177",
    alias4: "github-alt",
    alias5: "github-alt",
    prefix: "fab",
    unicode: "f113",
  },
  {
    id: "178",
    alias4: "github-square",
    alias5: "github-square",
    prefix: "fab",
    unicode: "f092",
  },
  {
    id: "179",
    alias4: "gitlab",
    alias5: "gitlab",
    prefix: "fab",
    unicode: "f296",
  },
  {
    id: "180",
    alias4: "gittip",
    alias5: "gratipay",
    prefix: "fab",
    unicode: "f184",
  },
  {
    id: "181",
    alias4: "glass",
    alias5: "glass-martini",
    prefix: "fas",
    unicode: "f000",
  },
  {
    id: "182",
    alias4: "glide",
    alias5: "glide",
    prefix: "fab",
    unicode: "f2a5",
  },
  {
    id: "183",
    alias4: "glide-g",
    alias5: "glide-g",
    prefix: "fab",
    unicode: "f2a6",
  },
  {
    id: "184",
    alias4: "google",
    alias5: "google",
    prefix: "fab",
    unicode: "f1a0",
  },
  {
    id: "185",
    alias4: "google-plus",
    alias5: "google-plus-g",
    prefix: "fab",
    unicode: "f0d5",
  },
  {
    id: "186",
    alias4: "google-plus-circle",
    alias5: "google-plus",
    prefix: "fab",
    unicode: "f2b3",
  },
  {
    id: "187",
    alias4: "google-plus-official",
    alias5: "google-plus",
    prefix: "fab",
    unicode: "f2b3",
  },
  {
    id: "188",
    alias4: "google-plus-square",
    alias5: "google-plus-square",
    prefix: "fab",
    unicode: "f0d4",
  },
  {
    id: "189",
    alias4: "google-wallet",
    alias5: "google-wallet",
    prefix: "fab",
    unicode: "f1ee",
  },
  {
    id: "190",
    alias4: "gratipay",
    alias5: "gratipay",
    prefix: "fab",
    unicode: "f184",
  },
  {
    id: "191",
    alias4: "grav",
    alias5: "grav",
    prefix: "fab",
    unicode: "f2d6",
  },
  {
    id: "192",
    alias4: "group",
    alias5: "users",
    prefix: "fas",
    unicode: "f0c0",
  },
  {
    id: "193",
    alias4: "hacker-news",
    alias5: "hacker-news",
    prefix: "fab",
    unicode: "f1d4",
  },
  {
    id: "194",
    alias4: "hand-grab-o",
    alias5: "hand-rock",
    prefix: "fa",
    unicode: "f255",
  },
  {
    id: "195",
    alias4: "hand-lizard-o",
    alias5: "hand-lizard",
    prefix: "fa",
    unicode: "f258",
  },
  {
    id: "196",
    alias4: "hand-o-down",
    alias5: "hand-point-down",
    prefix: "fa",
    unicode: "f0a7",
  },
  {
    id: "197",
    alias4: "hand-o-left",
    alias5: "hand-point-left",
    prefix: "fa",
    unicode: "f0a5",
  },
  {
    id: "198",
    alias4: "hand-o-right",
    alias5: "hand-point-right",
    prefix: "fa",
    unicode: "f0a4",
  },
  {
    id: "199",
    alias4: "hand-o-up",
    alias5: "hand-point-up",
    prefix: "fa",
    unicode: "f0a6",
  },
  {
    id: "200",
    alias4: "hand-paper-o",
    alias5: "hand-paper",
    prefix: "fa",
    unicode: "f256",
  },
  {
    id: "201",
    alias4: "hand-peace-o",
    alias5: "hand-peace",
    prefix: "fa",
    unicode: "f25b",
  },
  {
    id: "202",
    alias4: "hand-pointer-o",
    alias5: "hand-pointer",
    prefix: "fa",
    unicode: "f25a",
  },
  {
    id: "203",
    alias4: "hand-rock-o",
    alias5: "hand-rock",
    prefix: "fa",
    unicode: "f255",
  },
  {
    id: "204",
    alias4: "hand-scissors-o",
    alias5: "hand-scissors",
    prefix: "fa",
    unicode: "f257",
  },
  {
    id: "205",
    alias4: "hand-spock-o",
    alias5: "hand-spock",
    prefix: "fa",
    unicode: "f259",
  },
  {
    id: "206",
    alias4: "hand-stop-o",
    alias5: "hand-paper",
    prefix: "fa",
    unicode: "f256",
  },
  {
    id: "207",
    alias4: "handshake-o",
    alias5: "handshake",
    prefix: "fa",
    unicode: "f2b5",
  },
  {
    id: "208",
    alias4: "hard-of-hearing",
    alias5: "deaf",
    prefix: "fas",
    unicode: "f2a4",
  },
  {
    id: "209",
    alias4: "hdd-o",
    alias5: "hdd",
    prefix: "fa",
    unicode: "f0a0",
  },
  {
    id: "210",
    alias4: "header",
    alias5: "heading",
    prefix: "fas",
    unicode: "f1dc",
  },
  {
    id: "211",
    alias4: "heart-o",
    alias5: "heart",
    prefix: "fa",
    unicode: "f004",
  },
  {
    id: "212",
    alias4: "hospital-o",
    alias5: "hospital",
    prefix: "fa",
    unicode: "f0f8",
  },
  {
    id: "213",
    alias4: "hotel",
    alias5: "bed",
    prefix: "fas",
    unicode: "f236",
  },
  {
    id: "214",
    alias4: "hourglass-1",
    alias5: "hourglass-start",
    prefix: "fas",
    unicode: "f251",
  },
  {
    id: "215",
    alias4: "hourglass-2",
    alias5: "hourglass-half",
    prefix: "fas",
    unicode: "f252",
  },
  {
    id: "216",
    alias4: "hourglass-3",
    alias5: "hourglass-end",
    prefix: "fas",
    unicode: "f253",
  },
  {
    id: "217",
    alias4: "hourglass-o",
    alias5: "hourglass",
    prefix: "fa",
    unicode: "f254",
  },
  {
    id: "218",
    alias4: "houzz",
    alias5: "houzz",
    prefix: "fab",
    unicode: "f27c",
  },
  {
    id: "219",
    alias4: "html5",
    alias5: "html5",
    prefix: "fab",
    unicode: "f13b",
  },
  {
    id: "220",
    alias4: "id-badge",
    alias5: "id-badge",
    prefix: "fa",
    unicode: "f2c1",
  },
  {
    id: "221",
    alias4: "id-card-o",
    alias5: "id-card",
    prefix: "fa",
    unicode: "f2c2",
  },
  {
    id: "222",
    alias4: "ils",
    alias5: "shekel-sign",
    prefix: "fas",
    unicode: "f20b",
  },
  {
    id: "223",
    alias4: "image",
    alias5: "image",
    prefix: "fa",
    unicode: "f03e",
  },
  {
    id: "224",
    alias4: "imdb",
    alias5: "imdb",
    prefix: "fab",
    unicode: "f2d8",
  },
  {
    id: "225",
    alias4: "inr",
    alias5: "rupee-sign",
    prefix: "fas",
    unicode: "f156",
  },
  {
    id: "226",
    alias4: "instagram",
    alias5: "instagram",
    prefix: "fab",
    unicode: "f16d",
  },
  {
    id: "227",
    alias4: "institution",
    alias5: "university",
    prefix: "fas",
    unicode: "f19c",
  },
  {
    id: "228",
    alias4: "internet-explorer",
    alias5: "internet-explorer",
    prefix: "fab",
    unicode: "f26b",
  },
  {
    id: "229",
    alias4: "intersex",
    alias5: "transgender",
    prefix: "fas",
    unicode: "f224",
  },
  {
    id: "230",
    alias4: "ioxhost",
    alias5: "ioxhost",
    prefix: "fab",
    unicode: "f208",
  },
  {
    id: "231",
    alias4: "joomla",
    alias5: "joomla",
    prefix: "fab",
    unicode: "f1aa",
  },
  {
    id: "232",
    alias4: "jpy",
    alias5: "yen-sign",
    prefix: "fas",
    unicode: "f157",
  },
  {
    id: "233",
    alias4: "jsfiddle",
    alias5: "jsfiddle",
    prefix: "fab",
    unicode: "f1cc",
  },
  {
    id: "234",
    alias4: "keyboard-o",
    alias5: "keyboard",
    prefix: "fa",
    unicode: "f11c",
  },
  {
    id: "235",
    alias4: "krw",
    alias5: "won-sign",
    prefix: "fas",
    unicode: "f159",
  },
  {
    id: "236",
    alias4: "lastfm",
    alias5: "lastfm",
    prefix: "fab",
    unicode: "f202",
  },
  {
    id: "237",
    alias4: "lastfm-square",
    alias5: "lastfm-square",
    prefix: "fab",
    unicode: "f203",
  },
  {
    id: "238",
    alias4: "leanpub",
    alias5: "leanpub",
    prefix: "fab",
    unicode: "f212",
  },
  {
    id: "239",
    alias4: "legal",
    alias5: "gavel",
    prefix: "fas",
    unicode: "f0e3",
  },
  {
    id: "240",
    alias4: "lemon-o",
    alias5: "lemon",
    prefix: "fa",
    unicode: "f094",
  },
  {
    id: "241",
    alias4: "level-down",
    alias5: "level-down-alt",
    prefix: "fas",
    unicode: "f3be",
  },
  {
    id: "242",
    alias4: "level-up",
    alias5: "level-up-alt",
    prefix: "fas",
    unicode: "f3bf",
  },
  {
    id: "243",
    alias4: "life-bouy",
    alias5: "life-ring",
    prefix: "fa",
    unicode: "f1cd",
  },
  {
    id: "244",
    alias4: "life-buoy",
    alias5: "life-ring",
    prefix: "fa",
    unicode: "f1cd",
  },
  {
    id: "245",
    alias4: "life-ring",
    alias5: "life-ring",
    prefix: "fa",
    unicode: "f1cd",
  },
  {
    id: "246",
    alias4: "life-saver",
    alias5: "life-ring",
    prefix: "fa",
    unicode: "f1cd",
  },
  {
    id: "247",
    alias4: "lightbulb-o",
    alias5: "lightbulb",
    prefix: "fa",
    unicode: "f0eb",
  },
  {
    id: "248",
    alias4: "line-chart",
    alias5: "chart-line",
    prefix: "fas",
    unicode: "f201",
  },
  {
    id: "249",
    alias4: "linkedin",
    alias5: "linkedin-in",
    prefix: "fab",
    unicode: "f0e1",
  },
  {
    id: "250",
    alias4: "linkedin-square",
    alias5: "linkedin",
    prefix: "fab",
    unicode: "f08c",
  },
  {
    id: "251",
    alias4: "linode",
    alias5: "linode",
    prefix: "fab",
    unicode: "f2b8",
  },
  {
    id: "252",
    alias4: "linux",
    alias5: "linux",
    prefix: "fab",
    unicode: "f17c",
  },
  {
    id: "253",
    alias4: "list-alt",
    alias5: "list-alt",
    prefix: "fa",
    unicode: "f022",
  },
  {
    id: "254",
    alias4: "long-arrow-down",
    alias5: "long-arrow-alt-down",
    prefix: "fas",
    unicode: "f309",
  },
  {
    id: "255",
    alias4: "long-arrow-left",
    alias5: "long-arrow-alt-left",
    prefix: "fas",
    unicode: "f30a",
  },
  {
    id: "256",
    alias4: "long-arrow-right",
    alias5: "long-arrow-alt-right",
    prefix: "fas",
    unicode: "f30b",
  },
  {
    id: "257",
    alias4: "long-arrow-up",
    alias5: "long-arrow-alt-up",
    prefix: "fas",
    unicode: "f30c",
  },
  {
    id: "258",
    alias4: "mail-forward",
    alias5: "share",
    prefix: "fas",
    unicode: "f064",
  },
  {
    id: "259",
    alias4: "mail-reply",
    alias5: "reply",
    prefix: "fas",
    unicode: "f3e5",
  },
  {
    id: "260",
    alias4: "mail-reply-all",
    alias5: "reply-all",
    prefix: "fas",
    unicode: "f122",
  },
  {
    id: "261",
    alias4: "map-marker",
    alias5: "map-marker-alt",
    prefix: "fas",
    unicode: "f3c5",
  },
  {
    id: "262",
    alias4: "map-o",
    alias5: "map",
    prefix: "fa",
    unicode: "f279",
  },
  {
    id: "263",
    alias4: "maxcdn",
    alias5: "maxcdn",
    prefix: "fab",
    unicode: "f136",
  },
  {
    id: "264",
    alias4: "meanpath",
    alias5: "font-awesome",
    prefix: "fab",
    unicode: "f2b4",
  },
  {
    id: "265",
    alias4: "medium",
    alias5: "medium",
    prefix: "fab",
    unicode: "f23a",
  },
  {
    id: "266",
    alias4: "meetup",
    alias5: "meetup",
    prefix: "fab",
    unicode: "f2e0",
  },
  {
    id: "267",
    alias4: "meh-o",
    alias5: "meh",
    prefix: "fa",
    unicode: "f11a",
  },
  {
    id: "268",
    alias4: "minus-square-o",
    alias5: "minus-square",
    prefix: "fa",
    unicode: "f146",
  },
  {
    id: "269",
    alias4: "mixcloud",
    alias5: "mixcloud",
    prefix: "fab",
    unicode: "f289",
  },
  {
    id: "270",
    alias4: "mobile",
    alias5: "mobile-alt",
    prefix: "fas",
    unicode: "f3cd",
  },
  {
    id: "271",
    alias4: "mobile-phone",
    alias5: "mobile-alt",
    prefix: "fas",
    unicode: "f3cd",
  },
  {
    id: "272",
    alias4: "modx",
    alias5: "modx",
    prefix: "fab",
    unicode: "f285",
  },
  {
    id: "273",
    alias4: "money",
    alias5: "money-bill-alt",
    prefix: "fa",
    unicode: "f3d1",
  },
  {
    id: "274",
    alias4: "moon-o",
    alias5: "moon",
    prefix: "fa",
    unicode: "f186",
  },
  {
    id: "275",
    alias4: "mortar-board",
    alias5: "graduation-cap",
    prefix: "fas",
    unicode: "f19d",
  },
  {
    id: "276",
    alias4: "navicon",
    alias5: "bars",
    prefix: "fas",
    unicode: "f0c9",
  },
  {
    id: "277",
    alias4: "newspaper-o",
    alias5: "newspaper",
    prefix: "fa",
    unicode: "f1ea",
  },
  {
    id: "278",
    alias4: "object-group",
    alias5: "object-group",
    prefix: "fa",
    unicode: "f247",
  },
  {
    id: "279",
    alias4: "object-ungroup",
    alias5: "object-ungroup",
    prefix: "fa",
    unicode: "f248",
  },
  {
    id: "280",
    alias4: "odnoklassniki",
    alias5: "odnoklassniki",
    prefix: "fab",
    unicode: "f263",
  },
  {
    id: "281",
    alias4: "odnoklassniki-square",
    alias5: "odnoklassniki-square",
    prefix: "fab",
    unicode: "f264",
  },
  {
    id: "282",
    alias4: "opencart",
    alias5: "opencart",
    prefix: "fab",
    unicode: "f23d",
  },
  {
    id: "283",
    alias4: "openid",
    alias5: "openid",
    prefix: "fab",
    unicode: "f19b",
  },
  {
    id: "284",
    alias4: "opera",
    alias5: "opera",
    prefix: "fab",
    unicode: "f26a",
  },
  {
    id: "285",
    alias4: "optin-monster",
    alias5: "optin-monster",
    prefix: "fab",
    unicode: "f23c",
  },
  {
    id: "286",
    alias4: "pagelines",
    alias5: "pagelines",
    prefix: "fab",
    unicode: "f18c",
  },
  {
    id: "287",
    alias4: "paper-plane-o",
    alias5: "paper-plane",
    prefix: "fa",
    unicode: "f1d8",
  },
  {
    id: "288",
    alias4: "paste",
    alias5: "clipboard",
    prefix: "fa",
    unicode: "f328",
  },
  {
    id: "289",
    alias4: "pause-circle-o",
    alias5: "pause-circle",
    prefix: "fa",
    unicode: "f28b",
  },
  {
    id: "290",
    alias4: "paypal",
    alias5: "paypal",
    prefix: "fab",
    unicode: "f1ed",
  },
  {
    id: "291",
    alias4: "pencil",
    alias5: "pencil-alt",
    prefix: "fas",
    unicode: "f303",
  },
  {
    id: "292",
    alias4: "pencil-square",
    alias5: "pen-square",
    prefix: "fas",
    unicode: "f14b",
  },
  {
    id: "293",
    alias4: "pencil-square-o",
    alias5: "edit",
    prefix: "fa",
    unicode: "f044",
  },
  {
    id: "294",
    alias4: "photo",
    alias5: "image",
    prefix: "fa",
    unicode: "f03e",
  },
  {
    id: "295",
    alias4: "picture-o",
    alias5: "image",
    prefix: "fa",
    unicode: "f03e",
  },
  {
    id: "296",
    alias4: "pie-chart",
    alias5: "chart-pie",
    prefix: "fas",
    unicode: "f200",
  },
  {
    id: "297",
    alias4: "pied-piper",
    alias5: "pied-piper",
    prefix: "fab",
    unicode: "f2ae",
  },
  {
    id: "298",
    alias4: "pied-piper-alt",
    alias5: "pied-piper-alt",
    prefix: "fab",
    unicode: "f1a8",
  },
  {
    id: "299",
    alias4: "pied-piper-pp",
    alias5: "pied-piper-pp",
    prefix: "fab",
    unicode: "f1a7",
  },
  {
    id: "300",
    alias4: "pinterest",
    alias5: "pinterest",
    prefix: "fab",
    unicode: "f0d2",
  },
  {
    id: "301",
    alias4: "pinterest-p",
    alias5: "pinterest-p",
    prefix: "fab",
    unicode: "f231",
  },
  {
    id: "302",
    alias4: "pinterest-square",
    alias5: "pinterest-square",
    prefix: "fab",
    unicode: "f0d3",
  },
  {
    id: "303",
    alias4: "play-circle-o",
    alias5: "play-circle",
    prefix: "fa",
    unicode: "f144",
  },
  {
    id: "304",
    alias4: "plus-square-o",
    alias5: "plus-square",
    prefix: "fa",
    unicode: "f0fe",
  },
  {
    id: "305",
    alias4: "product-hunt",
    alias5: "product-hunt",
    prefix: "fab",
    unicode: "f288",
  },
  { id: "306", alias4: "qq", alias5: "qq", prefix: "fab", unicode: "f1d6" },
  {
    id: "307",
    alias4: "question-circle-o",
    alias5: "question-circle",
    prefix: "fa",
    unicode: "f059",
  },
  {
    id: "308",
    alias4: "quora",
    alias5: "quora",
    prefix: "fab",
    unicode: "f2c4",
  },
  {
    id: "309",
    alias4: "ra",
    alias5: "rebel",
    prefix: "fab",
    unicode: "f1d0",
  },
  {
    id: "310",
    alias4: "ravelry",
    alias5: "ravelry",
    prefix: "fab",
    unicode: "f2d9",
  },
  {
    id: "311",
    alias4: "rebel",
    alias5: "rebel",
    prefix: "fab",
    unicode: "f1d0",
  },
  {
    id: "312",
    alias4: "reddit",
    alias5: "reddit",
    prefix: "fab",
    unicode: "f1a1",
  },
  {
    id: "313",
    alias4: "reddit-alien",
    alias5: "reddit-alien",
    prefix: "fab",
    unicode: "f281",
  },
  {
    id: "314",
    alias4: "reddit-square",
    alias5: "reddit-square",
    prefix: "fab",
    unicode: "f1a2",
  },
  {
    id: "315",
    alias4: "refresh",
    alias5: "sync",
    prefix: "fas",
    unicode: "f021",
  },
  {
    id: "316",
    alias4: "registered",
    alias5: "registered",
    prefix: "fa",
    unicode: "f25d",
  },
  {
    id: "317",
    alias4: "remove",
    alias5: "times",
    prefix: "fas",
    unicode: "f00d",
  },
  {
    id: "318",
    alias4: "renren",
    alias5: "renren",
    prefix: "fab",
    unicode: "f18b",
  },
  {
    id: "319",
    alias4: "reorder",
    alias5: "bars",
    prefix: "fas",
    unicode: "f0c9",
  },
  {
    id: "320",
    alias4: "repeat",
    alias5: "redo",
    prefix: "fas",
    unicode: "f01e",
  },
  {
    id: "321",
    alias4: "resistance",
    alias5: "rebel",
    prefix: "fab",
    unicode: "f1d0",
  },
  {
    id: "322",
    alias4: "rmb",
    alias5: "yen-sign",
    prefix: "fas",
    unicode: "f157",
  },
  {
    id: "323",
    alias4: "rotate-left",
    alias5: "undo",
    prefix: "fas",
    unicode: "f0e2",
  },
  {
    id: "324",
    alias4: "rotate-right",
    alias5: "redo",
    prefix: "fas",
    unicode: "f01e",
  },
  {
    id: "325",
    alias4: "rouble",
    alias5: "ruble-sign",
    prefix: "fas",
    unicode: "f158",
  },
  {
    id: "326",
    alias4: "rub",
    alias5: "ruble-sign",
    prefix: "fas",
    unicode: "f158",
  },
  {
    id: "327",
    alias4: "ruble",
    alias5: "ruble-sign",
    prefix: "fas",
    unicode: "f158",
  },
  {
    id: "328",
    alias4: "rupee",
    alias5: "rupee-sign",
    prefix: "fas",
    unicode: "f156",
  },
  {
    id: "329",
    alias4: "s15",
    alias5: "bath",
    prefix: "fas",
    unicode: "f2cd",
  },
  {
    id: "330",
    alias4: "safai",
    alias5: "safai",
    prefix: "fab",
    unicode: "f267",
  },
  {
    id: "331",
    alias4: "scissors",
    alias5: "cut",
    prefix: "fas",
    unicode: "f0c4",
  },
  {
    id: "332",
    alias4: "scribd",
    alias5: "scribd",
    prefix: "fab",
    unicode: "f28a",
  },
  {
    id: "333",
    alias4: "sellsy",
    alias5: "sellsy",
    prefix: "fab",
    unicode: "f213",
  },
  {
    id: "334",
    alias4: "send",
    alias5: "paper-plane",
    prefix: "fas",
    unicode: "f1d8",
  },
  {
    id: "335",
    alias4: "send-o",
    alias5: "paper-plane",
    prefix: "fa",
    unicode: "f1d8",
  },
  {
    id: "336",
    alias4: "share-square-o",
    alias5: "share-square",
    prefix: "fa",
    unicode: "f14d",
  },
  {
    id: "337",
    alias4: "shekel",
    alias5: "shekel-sign",
    prefix: "fas",
    unicode: "f20b",
  },
  {
    id: "338",
    alias4: "sheqel",
    alias5: "shekel-sign",
    prefix: "fas",
    unicode: "f20b",
  },
  {
    id: "339",
    alias4: "shield",
    alias5: "shield-alt",
    prefix: "fas",
    unicode: "f3ed",
  },
  {
    id: "340",
    alias4: "shirtsinbulk",
    alias5: "shirtsinbulk",
    prefix: "fab",
    unicode: "f214",
  },
  {
    id: "341",
    alias4: "sign-in",
    alias5: "sign-in-alt",
    prefix: "fas",
    unicode: "f2f6",
  },
  {
    id: "342",
    alias4: "sign-out",
    alias5: "sign-out-alt",
    prefix: "fas",
    unicode: "f2f5",
  },
  {
    id: "343",
    alias4: "signing",
    alias5: "sign-language",
    prefix: "fas",
    unicode: "f2a7",
  },
  {
    id: "344",
    alias4: "simplybuilt",
    alias5: "simplybuilt",
    prefix: "fab",
    unicode: "f215",
  },
  {
    id: "345",
    alias4: "skyatlas",
    alias5: "skyatlas",
    prefix: "fab",
    unicode: "f216",
  },
  {
    id: "346",
    alias4: "skype",
    alias5: "skype",
    prefix: "fab",
    unicode: "f17e",
  },
  {
    id: "347",
    alias4: "slack",
    alias5: "slack",
    prefix: "fab",
    unicode: "f198",
  },
  {
    id: "348",
    alias4: "sliders",
    alias5: "sliders-h",
    prefix: "fas",
    unicode: "f1de",
  },
  {
    id: "349",
    alias4: "slideshare",
    alias5: "slideshare",
    prefix: "fab",
    unicode: "f1e7",
  },
  {
    id: "350",
    alias4: "smile-o",
    alias5: "smile",
    prefix: "fa",
    unicode: "f118",
  },
  {
    id: "351",
    alias4: "snapchat",
    alias5: "snapchat",
    prefix: "fab",
    unicode: "f2ab",
  },
  {
    id: "352",
    alias4: "snapchat-ghost",
    alias5: "snapchat-ghost",
    prefix: "fab",
    unicode: "f2ac",
  },
  {
    id: "353",
    alias4: "snapchat-square",
    alias5: "snapchat-square",
    prefix: "fab",
    unicode: "f2ad",
  },
  {
    id: "354",
    alias4: "snowflake-o",
    alias5: "snowflake",
    prefix: "fa",
    unicode: "f2dc",
  },
  {
    id: "355",
    alias4: "soccer-ball-o",
    alias5: "futbol",
    prefix: "fa",
    unicode: "f1e3",
  },
  {
    id: "356",
    alias4: "sort-alpha-asc",
    alias5: "sort-alpha-down",
    prefix: "fas",
    unicode: "f15d",
  },
  {
    id: "357",
    alias4: "sort-alpha-desc",
    alias5: "sort-alpha-up",
    prefix: "fas",
    unicode: "f15e",
  },
  {
    id: "358",
    alias4: "sort-amount-asc",
    alias5: "sort-amount-down",
    prefix: "fas",
    unicode: "f160",
  },
  {
    id: "359",
    alias4: "sort-amount-desc",
    alias5: "sort-amount-up",
    prefix: "fas",
    unicode: "f161",
  },
  {
    id: "360",
    alias4: "sort-asc",
    alias5: "sort-up",
    prefix: "fas",
    unicode: "f0de",
  },
  {
    id: "361",
    alias4: "sort-desc",
    alias5: "sort-down",
    prefix: "fas",
    unicode: "f0dd",
  },
  {
    id: "362",
    alias4: "sort-numeric-asc",
    alias5: "sort-numeric-down",
    prefix: "fas",
    unicode: "f162",
  },
  {
    id: "363",
    alias4: "sort-numeric-desc",
    alias5: "sort-numeric-up",
    prefix: "fas",
    unicode: "f163",
  },
  {
    id: "364",
    alias4: "soundcloud",
    alias5: "soundcloud",
    prefix: "fab",
    unicode: "f1be",
  },
  {
    id: "365",
    alias4: "spoon",
    alias5: "utensil-spoon",
    prefix: "fas",
    unicode: "f2e5",
  },
  {
    id: "366",
    alias4: "spotify",
    alias5: "spotify",
    prefix: "fab",
    unicode: "f1bc",
  },
  {
    id: "367",
    alias4: "square-o",
    alias5: "square",
    prefix: "fa",
    unicode: "f0c8",
  },
  {
    id: "368",
    alias4: "stack-exchange",
    alias5: "stack-exchange",
    prefix: "fab",
    unicode: "f18d",
  },
  {
    id: "369",
    alias4: "stack-overflow",
    alias5: "stack-overflow",
    prefix: "fab",
    unicode: "f16c",
  },
  {
    id: "370",
    alias4: "star-half-empty",
    alias5: "star-half",
    prefix: "fa",
    unicode: "f089",
  },
  {
    id: "371",
    alias4: "star-half-full",
    alias5: "star-half",
    prefix: "fa",
    unicode: "f089",
  },
  {
    id: "372",
    alias4: "star-half-o",
    alias5: "star-half",
    prefix: "fa",
    unicode: "f089",
  },
  {
    id: "373",
    alias4: "star-o",
    alias5: "star",
    prefix: "fa",
    unicode: "f005",
  },
  {
    id: "374",
    alias4: "steam",
    alias5: "steam",
    prefix: "fab",
    unicode: "f1b6",
  },
  {
    id: "375",
    alias4: "steam-square",
    alias5: "steam-square",
    prefix: "fab",
    unicode: "f1b7",
  },
  {
    id: "376",
    alias4: "sticky-note-o",
    alias5: "sticky-note",
    prefix: "fa",
    unicode: "f249",
  },
  {
    id: "377",
    alias4: "stop-circle-o",
    alias5: "stop-circle",
    prefix: "fa",
    unicode: "f28d",
  },
  {
    id: "378",
    alias4: "stumbleupon",
    alias5: "stumbleupon",
    prefix: "fab",
    unicode: "f1a4",
  },
  {
    id: "379",
    alias4: "stumbleupon-circle",
    alias5: "stumbleupon-circle",
    prefix: "fab",
    unicode: "f1a3",
  },
  {
    id: "380",
    alias4: "sun-o",
    alias5: "sun",
    prefix: "fa",
    unicode: "f185",
  },
  {
    id: "381",
    alias4: "superpowers",
    alias5: "superpowers",
    prefix: "fab",
    unicode: "f2dd",
  },
  {
    id: "382",
    alias4: "support",
    alias5: "life-ring",
    prefix: "fa",
    unicode: "f1cd",
  },
  {
    id: "383",
    alias4: "tablet",
    alias5: "tablet-alt",
    prefix: "fas",
    unicode: "f3fa",
  },
  {
    id: "384",
    alias4: "tachometer",
    alias5: "tachometer-alt",
    prefix: "fas",
    unicode: "f3fd",
  },
  {
    id: "385",
    alias4: "telegram",
    alias5: "telegram",
    prefix: "fab",
    unicode: "f2c6",
  },
  {
    id: "386",
    alias4: "television",
    alias5: "tv",
    prefix: "fas",
    unicode: "f26c",
  },
  {
    id: "387",
    alias4: "tencent-weibo",
    alias5: "tencent-weibo",
    prefix: "fab",
    unicode: "f1d5",
  },
  {
    id: "388",
    alias4: "themeisle",
    alias5: "themeisle",
    prefix: "fab",
    unicode: "f2b2",
  },
  {
    id: "389",
    alias4: "thermometer",
    alias5: "thermometer-full",
    prefix: "fas",
    unicode: "f2c7",
  },
  {
    id: "390",
    alias4: "thermometer-0",
    alias5: "thermometer-empty",
    prefix: "fas",
    unicode: "f2cb",
  },
  {
    id: "391",
    alias4: "thermometer-1",
    alias5: "thermometer-quarter",
    prefix: "fas",
    unicode: "f2ca",
  },
  {
    id: "392",
    alias4: "thermometer-2",
    alias5: "thermometer-half",
    prefix: "fas",
    unicode: "f2c9",
  },
  {
    id: "393",
    alias4: "thermometer-3",
    alias5: "thermometer-three-quarters",
    prefix: "fas",
    unicode: "f2c8",
  },
  {
    id: "394",
    alias4: "thermometer-4",
    alias5: "thermometer-full",
    prefix: "fas",
    unicode: "f2c7",
  },
  {
    id: "395",
    alias4: "thumb-tack",
    alias5: "thumbtack",
    prefix: "fas",
    unicode: "f08d",
  },
  {
    id: "396",
    alias4: "thumbs-o-down",
    alias5: "thumbs-down",
    prefix: "fa",
    unicode: "f165",
  },
  {
    id: "397",
    alias4: "thumbs-o-up",
    alias5: "thumbs-up",
    prefix: "fa",
    unicode: "f164",
  },
  {
    id: "398",
    alias4: "ticket",
    alias5: "ticket-alt",
    prefix: "fas",
    unicode: "f3ff",
  },
  {
    id: "399",
    alias4: "times-circle-o",
    alias5: "times-circle",
    prefix: "fa",
    unicode: "f057",
  },
  {
    id: "400",
    alias4: "times-rectangle",
    alias5: "window-close",
    prefix: "fas",
    unicode: "f410",
  },
  {
    id: "401",
    alias4: "times-rectangle-o",
    alias5: "window-close",
    prefix: "fa",
    unicode: "f410",
  },
  {
    id: "402",
    alias4: "toggle-down",
    alias5: "caret-square-down",
    prefix: "fa",
    unicode: "f150",
  },
  {
    id: "403",
    alias4: "toggle-left",
    alias5: "caret-square-left",
    prefix: "fa",
    unicode: "f191",
  },
  {
    id: "404",
    alias4: "toggle-right",
    alias5: "caret-square-right",
    prefix: "fa",
    unicode: "f152",
  },
  {
    id: "405",
    alias4: "toggle-up",
    alias5: "caret-square-up",
    prefix: "fa",
    unicode: "f151",
  },
  {
    id: "406",
    alias4: "trash",
    alias5: "trash-alt",
    prefix: "fas",
    unicode: "f2ed",
  },
  {
    id: "407",
    alias4: "trash-o",
    alias5: "trash-alt",
    prefix: "fa",
    unicode: "f2ed",
  },
  {
    id: "408",
    alias4: "trello",
    alias5: "trello",
    prefix: "fab",
    unicode: "f181",
  },
  {
    id: "409",
    alias4: "tripadvisor",
    alias5: "tripadvisor",
    prefix: "fab",
    unicode: "f262",
  },
  {
    id: "410",
    alias4: "try",
    alias5: "lira-sign",
    prefix: "fas",
    unicode: "f195",
  },
  {
    id: "411",
    alias4: "tumblr",
    alias5: "tumblr",
    prefix: "fab",
    unicode: "f173",
  },
  {
    id: "412",
    alias4: "tumblr-square",
    alias5: "tumblr-square",
    prefix: "fab",
    unicode: "f174",
  },
  {
    id: "413",
    alias4: "turkish-lira",
    alias5: "lira-sign",
    prefix: "fas",
    unicode: "f195",
  },
  {
    id: "414",
    alias4: "twitch",
    alias5: "twitch",
    prefix: "fab",
    unicode: "f1e8",
  },
  {
    id: "415",
    alias4: "twitter",
    alias5: "twitter",
    prefix: "fab",
    unicode: "f099",
  },
  {
    id: "416",
    alias4: "twitter-square",
    alias5: "twitter-square",
    prefix: "fab",
    unicode: "f081",
  },
  {
    id: "417",
    alias4: "unsorted",
    alias5: "sort",
    prefix: "fas",
    unicode: "f0dc",
  },
  {
    id: "418",
    alias4: "usb",
    alias5: "usb",
    prefix: "fab",
    unicode: "f287",
  },
  {
    id: "419",
    alias4: "usd",
    alias5: "dollar-sign",
    prefix: "fas",
    unicode: "f155",
  },
  {
    id: "420",
    alias4: "user-circle-o",
    alias5: "user-circle",
    prefix: "fa",
    unicode: "f2bd",
  },
  {
    id: "421",
    alias4: "user-o",
    alias5: "user",
    prefix: "fa",
    unicode: "f007",
  },
  {
    id: "422",
    alias4: "vcard",
    alias5: "address-card",
    prefix: "fas",
    unicode: "f2bb",
  },
  {
    id: "423",
    alias4: "vcard-o",
    alias5: "address-card",
    prefix: "fa",
    unicode: "f2bb",
  },
  {
    id: "424",
    alias4: "viacoin",
    alias5: "viacoin",
    prefix: "fab",
    unicode: "f237",
  },
  {
    id: "425",
    alias4: "viadeo",
    alias5: "viadeo",
    prefix: "fab",
    unicode: "f2a9",
  },
  {
    id: "426",
    alias4: "viadeo-square",
    alias5: "viadeo-square",
    prefix: "fab",
    unicode: "f2aa",
  },
  {
    id: "427",
    alias4: "video-camera",
    alias5: "video",
    prefix: "fas",
    unicode: "f03d",
  },
  {
    id: "428",
    alias4: "vimeo",
    alias5: "vimeo-v",
    prefix: "fab",
    unicode: "f27d",
  },
  {
    id: "429",
    alias4: "vimeo-square",
    alias5: "vimeo-square",
    prefix: "fab",
    unicode: "f194",
  },
  {
    id: "430",
    alias4: "vine",
    alias5: "vine",
    prefix: "fab",
    unicode: "f1ca",
  },
  { id: "431", alias4: "vk", alias5: "vk", prefix: "fab", unicode: "f189" },
  {
    id: "432",
    alias4: "volume-control-phone",
    alias5: "phone-volume",
    prefix: "fas",
    unicode: "f2a0",
  },
  {
    id: "433",
    alias4: "warning",
    alias5: "exclamation-triangle",
    prefix: "fas",
    unicode: "f071",
  },
  {
    id: "434",
    alias4: "wechat",
    alias5: "weixin",
    prefix: "fab",
    unicode: "f1d7",
  },
  {
    id: "435",
    alias4: "weibo",
    alias5: "weibo",
    prefix: "fab",
    unicode: "f18a",
  },
  {
    id: "436",
    alias4: "weixin",
    alias5: "weixin",
    prefix: "fab",
    unicode: "f1d7",
  },
  {
    id: "437",
    alias4: "whatsapp",
    alias5: "whatsapp",
    prefix: "fab",
    unicode: "f232",
  },
  {
    id: "438",
    alias4: "wheelchair-alt",
    alias5: "accessible-icon",
    prefix: "fab",
    unicode: "f368",
  },
  {
    id: "439",
    alias4: "wikipedia-w",
    alias5: "wikipedia-w",
    prefix: "fab",
    unicode: "f266",
  },
  {
    id: "440",
    alias4: "window-close-o",
    alias5: "window-close",
    prefix: "fa",
    unicode: "f410",
  },
  {
    id: "441",
    alias4: "window-maximize",
    alias5: "window-maximize",
    prefix: "fa",
    unicode: "f2d0",
  },
  {
    id: "442",
    alias4: "window-restore",
    alias5: "window-restore",
    prefix: "fa",
    unicode: "f2d2",
  },
  {
    id: "443",
    alias4: "windows",
    alias5: "windows",
    prefix: "fab",
    unicode: "f17a",
  },
  {
    id: "444",
    alias4: "won",
    alias5: "won-sign",
    prefix: "fas",
    unicode: "f159",
  },
  {
    id: "445",
    alias4: "wordpress",
    alias5: "wordpress",
    prefix: "fab",
    unicode: "f19a",
  },
  {
    id: "446",
    alias4: "wpbeginner",
    alias5: "wpbeginner",
    prefix: "fab",
    unicode: "f297",
  },
  {
    id: "447",
    alias4: "wpexplorer",
    alias5: "wpexplorer",
    prefix: "fab",
    unicode: "f2de",
  },
  {
    id: "448",
    alias4: "wpforms",
    alias5: "wpforms",
    prefix: "fab",
    unicode: "f298",
  },
  {
    id: "449",
    alias4: "xing",
    alias5: "xing",
    prefix: "fab",
    unicode: "f168",
  },
  {
    id: "450",
    alias4: "xing-square",
    alias5: "xing-square",
    prefix: "fab",
    unicode: "f169",
  },
  {
    id: "451",
    alias4: "y-combinator",
    alias5: "y-combinator",
    prefix: "fab",
    unicode: "f23b",
  },
  {
    id: "452",
    alias4: "y-combinator-square",
    alias5: "hacker-news",
    prefix: "fab",
    unicode: "f1d4",
  },
  {
    id: "453",
    alias4: "yahoo",
    alias5: "yahoo",
    prefix: "fab",
    unicode: "f19e",
  },
  {
    id: "454",
    alias4: "yc",
    alias5: "y-combinator",
    prefix: "fab",
    unicode: "f23b",
  },
  {
    id: "455",
    alias4: "yc-square",
    alias5: "hacker-news",
    prefix: "fab",
    unicode: "f1d4",
  },
  {
    id: "456",
    alias4: "yelp",
    alias5: "yelp",
    prefix: "fab",
    unicode: "f1e9",
  },
  {
    id: "457",
    alias4: "yen",
    alias5: "yen-sign",
    prefix: "fas",
    unicode: "f157",
  },
  {
    id: "458",
    alias4: "yoast",
    alias5: "yoast",
    prefix: "fab",
    unicode: "f2b1",
  },
  {
    id: "459",
    alias4: "youtube",
    alias5: "youtube",
    prefix: "fab",
    unicode: "f167",
  },
  {
    id: "460",
    alias4: "youtube-play",
    alias5: "youtube",
    prefix: "fab",
    unicode: "f167",
  },
  {
    id: "461",
    alias4: "youtube-square",
    alias5: "youtube-square",
    prefix: "fab",
    unicode: "f431",
  },
];
